experiments = [
    # 1
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "3000",
            "--random-output-len": "300",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 2
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "4000",
            "--random-output-len": "300",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "1000",
            "--max-prefix-tokens": "2000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 3
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "3000",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 4
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "300",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 5
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "300",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "200",
            "--max-prefix-tokens": "300",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
]



experiments = [
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "8192",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "4096",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "2048",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "1024",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "512",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "500",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
]

experiments = [
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "4096",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "2048",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "1024",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "512",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "256",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "128",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "64",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random",
            "--random-input-len": "4096",
            "--random-output-len": "1000",
            "--random-range-ratio": "0.3",
            "--seed": "42",
            "--max-concurrency": "185",
            "--num-prompts": "80",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
]