experiments = [
    # 1
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "3000",
            "--random-output-len": "300",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 2
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "4000",
            "--random-output-len": "300",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "1000",
            "--max-prefix-tokens": "2000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 3
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "3000",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 4
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "300",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "2000",
            "--max-prefix-tokens": "3000",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
    # 5
    {
        "server_args": {
            "--max-num-batched-tokens": "16384",
            "--max-model-len": "16384",
            "--long-prefill-token-threshold": "0",
            "--enable-prefix-caching": None,
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--tensor-parallel-size": "1",
            "--gpu-memory-utilization": "0.9",
            "--port": "8001",
        },
        "client_args": {
            "--model": "/nas_aisw/datasets/checkpoints/LLM/Qwen3-30B-A3B",
            "--dataset-name": "random_prefix_sharing",
            "--random-input-len": "300",
            "--random-output-len": "3000",
            "--random-range-ratio": "0.5",
            "--seed": "42",
            "--prefix-glossary-size": "40",
            "--prefix-sharing-strength": "1.0",
            "--min-prefix-tokens": "200",
            "--max-prefix-tokens": "300",
            "--max-concurrency": "185",
            "--num-prompts": "100",
            "--append-result": None,
            "--result-filename": "/mnt/ssd/mayiling.myl/output/benchmark_results.json",
            "--port": "8001",
        },
    },
]